language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
before_install:
  - source travis_java_install.sh
install:
  - pip install -r requirements.txt
env:
  global:
    - JAVA_HOME=${JAVA_HOME:=$(/usr/libexec/java_home)}
    - WORKSPACE=${WORKSPACE:=.}
    - NEXUS_PASS=${NEXUS_PASS:=sbt_creds}
    - NEXUS_USER=${NEXUS_USER:=sbt}
script:
  - py.test -v --junitxml results.xml test/
services:
  - mongodb
