sudo: false
language: python
python:
  - "2.7"
jdk:
  - oraclejdk8
install:
  - pip install -r requirements.txt
env:
  global:
    - JAVA_HOME=${JAVA_HOME:=$(/usr/libexec/java_home)}
    - WORKSPACE=${WORKSPACE:=.}
    - NEXUS_PASS=${NEXUS_PASS:=fake}
    - NEXUS_USER=${NEXUS_USER:=fake}
script:
  - py.test -v --junitxml results.xml test/tests.py
  - py.test -v --junitxml results.xml test/unit
services:
  - mongodb
